#!/bin/sh

python -m createmap.tools "$@"

# ./cm  --help
# ./cm npfilt -i data/point_cloud.npy -c data/conf.json -o data/point_cloud_filtered.npy
# ./cm np2geom -i data/point_cloud_filtered.npy -c data/conf.json -o data/point_cloud_map.json